---
global:
  pattern: multicloud-gitops
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
  helloMessage: Hello world from values-global.yaml
main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
